# Generated by Django 5.1.3 on 2024-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_list', '0002_alter_faculty_dean_alter_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
