# Generated by Django 5.1.3 on 2024-11-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_list', '0004_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'number']},
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='tutor',
            name='forenames',
            field=models.CharField(default='John', max_length=64),
        ),
        migrations.AddField(
            model_name='tutor',
            name='surname',
            field=models.CharField(default='Smith', max_length=64),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(choices=[('Leighton', 'Leighton'), ('Priestley', 'Priestley')], max_length=12),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_list.faculty'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_list.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'building')},
        ),
    ]
