# Generated by Django 5.1.3 on 2024-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_list', '0005_alter_faculty_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['surname', 'forenames']},
        ),
        migrations.AddField(
            model_name='tutor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='forenames',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='surname',
            field=models.CharField(max_length=64),
        ),
    ]
